### PR TITLE
This change allows twilight-commander to exit on the first "file-action"

### PR DESCRIPTION
**Pull request by marcesquerra**
The idea is to be able to use twilight-commander as a one-of file selector (for example, select the file I want to edit)

### CODE REVIEW

**Comment by golmman** [comment]
Nice addition, thank you.

It looks like there is some heavy computing going on when i start it with your changes.
Maybe this loop [here](https://github.com/golmman/twilight-commander/pull/9/files#diff-f5c6b18d6de83b85d54c38a1da74b9124a5587b7d7b8474838571eb6eb169263R14) could be the problem?

Here is my `top` output, when i run your version (note the 100% cpu utilization): 
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  58448 ****      20   0  141356   3732   3484 S 100.0   0.0   0:14.36 twilight-comman
```

**Comment by marcesquerra** [comment]
That might well be... I haven't tested this in depth tbh, and I been thinking that could be a problem since yesterday. Let me see if this can be improved.

**Comment by marcesquerra** [comment]
You are totally right, I reproduced the error and was exactly the same. I made a change that fixes the issue for me, if you want to try that :)

**Comment by golmman** [comment]
Thanks again for contributing!

**Pull request merged**
