### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by golmman** [comment]
Hi and thanks! How did you tell `cargo fmt` to make those changes? I run cargo fmt before each commit but i am apparently getting a different formatting.

**Comment by Atul9** [comment]
I just ran `cargo fmt` and those changes were done.

**Comment by Atul9** [comment]
@golmman I have resolved the merge conflicts, please check

**Comment by golmman** [comment]
I just checked out your branch and performed a `cargo fmt`: all your changes are going to be reverted. So there is no point in merging this pull request.
Thanks anyway.

**Pull request closed without merging**
